//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FoodEvent>()
                   .Property(e => e.Latitude)
                   .HasPrecision(10, 8);

            modelBuilder.Entity<FoodEvent>()
                .Property(e => e.Longitude)
                .HasPrecision(11, 8);
            ////throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FoodEvent> FoodEventSet { get; set; }
    }
}
